### ISSUE TITLE
Creative Commons / MIT / Apache License Everything

### ISSUE THREAD

**Issue by TCROC** [crablang/crablang#7]
Make sure crab, crablang, crusty, crabby, or whatever we decided to call our tools and terminology are licensed as openly as possible.  We want to make sure nobody takes them away from us.

**Comment by trvswgnr** [comment]
does this section seem to cover everything or am i missing something?

https://github.com/crablang/crablang#trademark

**Comment by TCROC** [comment]
It's simple, perfect, and puts our crabs in public domain for ever ❤️
